squashed back to single action

diff --git a/.github/workflows/create-releases.yml b/.github/workflows/create-releases.yml
--- a/.github/workflows/create-releases.yml
+++ b/.github/workflows/create-releases.yml
@@ -28,11 +28,15 @@ jobs:
                 TAG_VERSION=${TAG##*-v} # Extract substring after '-v'
                 MANIFEST_VERSION=$(grep -oP '"version":\s*"\K[0-9.]+' manifest/template-manifest.json) # Get version from manifest
 
+                PRERELEASE=$([ "${{ env.TAG_VERSION }}" != "${{ env.MANIFEST_VERSION }}" ] && echo "true" || echo "false")
+
                 echo "TRIGGERING_TAG=$TAG" >> $GITHUB_ENV
                 echo "BROWSER=$BROWSER" >> $GITHUB_ENV
                 echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
                 echo "MANIFEST_VERSION=$MANIFEST_VERSION" >> $GITHUB_ENV
                 echo "BROWSER_VERSION_NAME=${{ env.AWSF }}-$BROWSER-v$MANIFEST_VERSION" >> $GITHUB_ENV
+                echo "RELEASE_NOTES=\"./docs/Release Notes/v${{ env.TAG_VERSION }}.md\"" >> $GITHUB_ENV
+                echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV
 
             - name: Build Extension
               if: env.TAG_VERSION == env.MANIFEST_VERSION
@@ -43,3 +47,28 @@ jobs:
                   release_notes: "./docs/Release Notes/v${{ env.TAG_VERSION }}.md"
                   release_name: ${{ env.BROWSER_VERSION_NAME }}
                   target_tag: ${{ env.TRIGGERING_TAG }}
+
+            - name: Make Manifest
+              run: |
+                deno task dev-${{ inputs.target_browser }}
+                ls manifest.json # if the file does not exist, fails the script
+
+            - name: Create ${{ inputs.target_browser }} Release
+              uses: softprops/action-gh-release@v2.2.0
+              with:
+                name: ${{ env.BROWSER_VERSION_NAME }}
+                body: See release notes at ${{ env.RELEASE_NOTES }}.
+                body_path: ${{ env.RELEASE_NOTES }}
+                generate_release_notes: true
+                make_latest: true
+                tag_name: ${{ env.TRIGGERING_TAG }}
+                prerelease: ${{ env.PRERELEASE }}
+                files: |
+                  action
+                  assets
+                  background
+                  salesforce
+                  *.js
+                  LICENSE*
+                  README.md
+                  manifest.json
