fail after commenting

diff --git a/.github/workflows/pr-tests.yml b/.github/workflows/pr-tests.yml
--- a/.github/workflows/pr-tests.yml
+++ b/.github/workflows/pr-tests.yml
@@ -36,10 +36,9 @@ jobs:
               continue-on-error: true
               run: |
                 # Run the Deno linter and capture stderr
-                deno task lint 2> lint-error.log
+                deno task lint 2> lint-error.log || true # do not fail
 
             - name: Comment on PR if linter fails
-              if: failure()
               uses: actions/github-script@v7
               with:
                 script: |
@@ -63,6 +62,9 @@ jobs:
                     repo: context.repo.repo,
                     body: `## Linter Failed:\n\n\`\`\`${cleanErrorOutput}\`\`\``
                   });
+                  
+                  // fail due to error found on previous step
+                  process.exit(1);
 
             - name: Remove lint-error.log
               run: rm lint-error.log
