use github script

diff --git a/.github/workflows/pr-tests.yml b/.github/workflows/pr-tests.yml
--- a/.github/workflows/pr-tests.yml
+++ b/.github/workflows/pr-tests.yml
@@ -31,18 +31,28 @@ jobs:
                 git switch "${{ github.head_ref }}"
 
             - name: Run linter and comment on failure
-              run: |
-                output=$(deno task lint 2>&1 || true)
-                if [ -n "$output" ]; then
-                  PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
-                  echo "$PR_NUMBER"
-                  COMMENT_BODY="## Linter Failed:\n\n\`\`\`$(echo "$output")\`\`\`"
-                  curl -H "Authorization: token ${{ github.token }}" \
-                        -X POST \
-                        -d '{"body": "$COMMENT_BODY"}' \
-                        "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
-                  exit 2
-                fi
+              uses: actions/github-script@v7
+              with:
+                github-token: ${{ secrets.GITHUB_TOKEN }}
+                #script: |
+                run: |
+                  output=$(deno task lint 2>&1 || true)
+                  if [ -n "$output" ]; then
+                    PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
+                    echo "$PR_NUMBER"
+                    COMMENT_BODY="## Linter Failed:\n\n\`\`\`$(echo "$output")\`\`\`"
+                    github.rest.issues.createComment({
+                      issue_number: context.issue.number,
+                      owner: context.repo.owner,
+                      repo: context.repo.repo,
+                      body: '👋 Thanks for reporting!'
+                    })
+                    #curl -H "Authorization: token ${{ github.token }}" \
+                    #      -X POST \
+                    #      -d '{"body": "$COMMENT_BODY"}' \
+                    #      "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
+                    #exit 2
+                  fi
 
             - name: Verify formatting
               run: deno task fmt
