send comment when linter fails

diff --git a/.github/workflows/pr-tests.yml b/.github/workflows/pr-tests.yml
--- a/.github/workflows/pr-tests.yml
+++ b/.github/workflows/pr-tests.yml
@@ -27,7 +27,23 @@ jobs:
               run: git switch "${{ github.head_ref }}"
 
             - name: Run linter
-              run: deno task lint
+              run: |
+                output=$(deno task lint 2>&1)
+                echo "$output" > lint_output.txt
+                if [ $? -ne 0 ]; then
+                  exit 1
+                fi
+
+            - name: Post comment on PR if linter fails
+              if: failure()  # This step runs only if the previous step fails
+              run: |
+                PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
+                COMMENT_BODY="## Linter Failed\n\nHere is the output of the linter:\n\n\`\`\`$(cat lint_output.txt)\`\`\`"
+                curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+                     -X POST \
+                     -d "{\"body\": \"$COMMENT_BODY\"}" \
+                     "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
+
 
             - name: Verify formatting
               run: deno task fmt
